### PR TITLE
add cloneable

### PR DESCRIPTION
**Pull request by Liujianfu**
add a function of removing item when being dropped out
fix bug of dragelement's position incorect when using body as containment

### CODE REVIEW

**Comment by a5hik** [comment]
Hi thanks for the PR, Please elaborate the changes and the features you added.

Hope you had done a good testing. would appreciate If you provide an updated patch.

For instance, I do not see why you had added a CSS here 969ff53

**Comment by Liujianfu** [comment]
the CSS is for testing purpose, should be removed. I will do some thorough testing. after that, I will make a update patch.
 
Date: Tue, 16 Jun 2015 23:02:55 -0700

**Comment by a5hik** [comment]
Hope you had tested 3d60e8c , and let me also apply the patch and verify.

**Comment by a5hik** [comment]
this is addressed via #3 .

**Pull request closed without merging**
