### PR TITLE
Paginated list issue resolution

### PR DESCRIPTION
**Pull request by pcan**
Changed index management for 'asSortableItem' directive. When the item list is paginated (using a startFrom and limitTo filter on the item collection), the $index variable on the scope still refers to the first page elements. In this way, moving an item on the list (at page >= 2), causes a change on the first page, and the order on the current page remains the same. The only way to refer to the right item is to add a 'ngModel' directive (with a bit of redundancy), without using the $index at all. NgModel requirement has been marked as not mandatory (question mark in the 'require' field), so the old behaviour is preserved. Demo here (with patch): http://plnkr.co/edit/EPd1xE?p=preview

### CODE REVIEW

**Comment by a5hik** [comment]
This is Great!. I would prefer the plunkr example added as a sample in the 'demo' project.

**Comment by a5hik** [comment]
Also the README needs to include this changes.

**Comment by pcan** [comment]
Thank you. Oh, I just found a boundary-case for the debug=off fix, which issues a undefined-reference error. I'm going to issue another PR to fix that.

**Comment by a5hik** [comment]
Yeah, this was causing an issue -
sourceScope = elementClicked.data().$asSortableItemHandleController.scope;
I just revert it to the original on the master.

Your are welcome to send the PR.

**Pull request merged**
