### PR TITLE
Add CtrlClone feature

### PR DESCRIPTION
**Pull request by marius-bughiu**
Allows users to initiate the cloning process by holding Ctrl while dragging. All you have to do is to specify ctrlClone: true in the sortable options for this to work. 

I chose to create a new option instead of modifying the existing one (clone) in order to maintain backward compatibility.

Also, in my opinion, the current clone functionality is more of a 'readOnly' functionality than a clone. When clone is set to true you cannot drop anything in that sortable. That's not what should happen in my opinion. Maybe this can be rewritten in a future major version.

Usecase: imagine a task board where you can move tasks around between days. At some point you want to duplicate a task. Just ctrl+drag and you can duplicate your task.

Let me know if you have any questions / changes are required.

### CODE REVIEW

**Comment by a5hik** [comment]
Nice work..will look in to the PR.

**Comment by marius-bughiu** [comment]
Thanks. I've missed one thing when making the apply that would break the existing clone functionality. The last commit ought to fix it.

**Comment by a5hik** [comment]
@marius-bughiu 

- Also, in my opinion, the current clone functionality is more of a 'readOnly' functionality than a clone. When clone is set to true you cannot drop anything in that sortable.

Is the problem you come with the new ctrl option. If so we could try solve this in providing options. 
also when I merged the PR I couldn't really get the clone working . Am I missing something?

**Comment by marius-bughiu** [comment]
Hey, sorry for the late reply.
@a5hik could you tell me in which browser you tested? I'm not having any problems in Firefox or Chrome.
In IE the plugin is broken (drag ain't working at all). See issue #262

**Pull request merged**
