### PR TITLE
Fix #144 - avoid using element.scope()

### LINKED ISSUE #144: can't use ng-sortable with debugger info disabled
hi,
if i disable the debugger info (  $compileProvider.debugInfoEnabled(false); )
the library doesn't work, because it cannot find the scope of the DOM element - got undefined

here is the same problem - https://github.com/angular/angular.js/issues/9515
and they fix it

### PR DESCRIPTION
**Pull request by oori**
Fixes: https://github.com/a5hik/ng-sortable/issues/144
Related with: https://github.com/angular/angular.js/issues/9515

debugInfoEnabled(false) added to demo app.

### CODE REVIEW

**Comment by oori** [comment]
@a5hik I've looked into solving this by re-writing all related code to avoid using scope at all.   it is simple for "isDraggable",  but more complex for "dragMove".     after some iterations, I've opted for the .data('_scope') solution.    it is most efficient (that's how angular ng-scope works..),  and required the least changes.         I left relevant comment #144 in the code, for whatever future re-write.

**Comment by oori** [comment]
@a5hik ...please, after you pull these, would be great if you bump up the version. see: https://github.com/a5hik/ng-sortable/pull/148.    
 I'm (too much) bower-automation-dependant..

**Comment by a5hik** [comment]
@oori thanks for the PR. will look in to it.

**Comment by a5hik** [comment]
thanks this is pushed to the master.

**Pull request closed without merging**
