### PR TITLE
update model data only if item has really moved some where

### PR DESCRIPTION
**Pull request by canner85**
I had a Problem with "not really moving" sortable items...

I had a list of items in my sortable list. After a successful position change of an item, some data of this item was updated via an ajax call. When I tried to move the item again but released the item at a position on the screen outside my sorting list, the DOM was reseted to its original state before the drag. That was fine, but the data of the item changed to the data it had before the first (!) sorting started (to the initial data when the page was loaded).

So I added a check inside the dragEnd method, whether the item has changed its position at all. Only than, the model data of the item should be updated.

This fix worked for my purposes. Please let me know, if you can confirm this bug (and bugfix).

### CODE REVIEW

**Comment by a5hik** [comment]
@canner85 you need to do your business logics by implementing the callbacks exposed. 

itemMoved and orderChanged. please see the demo source.

If this is the case you will not have any issues.

**Comment by canner85** [comment]
@a5hik of course, I have all the business logic implemented in the callbacks, orderChanged for the same parent, itemMoved for moving across lists.

The data comes from a mongo DB. The position of the elements are saved inside mongo. So each time an item has been dragged, an ajax call saves the new position. In fact, moving one item will change multiple item's position at one drag. All items involved will get a new "_etag" in mongo which is required for modifying data at all. That's why the data source of the sorting lists will be replaced each time after an ajax update call.
Is this somehow comprehensible?

Everything is working fine with this procedure, except this case:
1. load the page
2. change order of the items (e.g. position 2 to 1)
3. ajax call updates data
4. sortable data is renewed
5. move the first (or last) item out of the list and release it
6. DOM resets
7. BUT: item's data has been reset to step 1. (from example in step 2.: position is not 1, but 2)

Neither orderChanged nor itemMoved is triggered in step 5

I try to give you a really simplified version of the code...
```javascript
$scope.sortableOptions = {
  orderChanged: orderChanged,
  itemMoved: function(event) {
    orderChanged(event, true);
  }
};
$scope.$on('dataChanged', getData);

getData();

function getData() {
  // simplified...
  $scope.data1 = DataService.getData(1);
  $scope.data2 = DataService.getData(2);
}

function orderChanged(event, acrossList) {
  var item = event.source.itemScope.item,
      position = event.dest.index + 1,
      type = item.type;

  $timeout(function() {
    /**
     * here DataService will fire ajax call, save the new data
     * and broadcast the 'dataChanged' event where the scope
     * vars are updated
     */
    if (acrossList) {
      DataService.saveDataAsOpposite(item, position);
    } else {
      DataService.saveData(item, type, position);
    }
  });
}
```

**Comment by a5hik** [comment]
@canner85 i'm not getting, my question is why don't you perform your ajax call in orderChanged or in itemMoved. still you can get the changed position of the elements?

**Comment by canner85** [comment]
@a5hik the ajax call is performed in orderChanged (as I commented in the JS code). When an item is really moved and its position changed, the orderChanged method is triggered, the ajax request is performed and everything works like a charm.
My problem occurs only as i described in the 7 steps... step 1 to 4 is fine (but required for the bug)... only the second attempt from step 5 on is buggy or me. I will try to set up a live example. It seems hard to explain by words.

**Pull request closed without merging**
