### PR TITLE
Fix #241 Drag and drop have trembling with blocks of different size

### LINKED ISSUE #241: Drag and drop have trembling with blocks of different size
Hello! 
Thank you for this plugin. 

There is one problem with drag and drop when you create blocks that have different sizes. Here is the copy of Plunker example you provide: http://plnkr.co/edit/EWqazPMfnUa12pR5lsjI?p=preview
There is one small change in this copy - third block is much bigger that another ones. You can see the bug if you drag  item1 and slowly move it over the big block. You can see annoying trembling.

Do you have any idea how this problem could be solved? 

Thanks in advance.

### PR DESCRIPTION
**Pull request by dizel3d**
Also I have updated "Simple" and "Horizontal" demo with different block sizes to to check my fix #241.
@ilyanaruson's [example](http://plnkr.co/edit/Ij9KRtysiHJ1GxEZ0jLk?p=preview) and @MelanieMenard's [example](http://plnkr.co/edit/oFm7oXsqpAkOZL8Qy0ka?p=preview) work correctly too with my fix.

### CODE REVIEW

**Comment by a5hik** [comment]
Thanks for the PR will look in to this.

**Comment by felippenardi** [comment]
Looking forward for this :+1:

**Comment by a5hik** [comment]
@dizel3d I had merged the PR and it looks good also added your demo to the main demo page.

**Comment by ilyanaruson** [comment]
Good news, great, thank you!

**Pull request merged**
