### PR TITLE
as-sortable-item-handle act as boolean condition

### PR DESCRIPTION
**Pull request by DocX**
This patch adds ability to set value to as-sortable-item-handle attribute - that when it is runtime evaluated to false, it disable dragging with that handle.

### CODE REVIEW

**Comment by a5hik** [comment]
@DocX can you plz provide a real time use case for this change. I try to understand the need for this change.

- Ashik

**Comment by DocX** [comment]
I have some items in the list, that I don't want to be moveable. My real use case is ordeder list of tasks, so user can be reordering tasks in the list. But they are processed sequentially (by external processor), and once they are processed, they cannot be moved obviously - and stay on top.

I haven't found another way to do this, via "accept" callback, because accept is not called with the item in parameters, only the source and dest list - which i cannot use to evaluate condition on the actual item.. So I put this evaluation directly in the handle. If there is a way I don't see, please let me know ;)

**Comment by a5hik** [comment]
accept will have three parameters.. 
sourceItemHandleScope, destScope, destItemScope

But this will prevent the drop, but looks like your case is to prevent the drag.  Did you tried applying no-drag on the element once it is processed.

**Comment by DocX** [comment]
Yep I want to prevent drag.

How do you apply no-drag attribute conditionally and in runtime - after
template compile? I need to have it based on scope model value.
Dne 14. 5. 2015 8:47 napsal uživatel "Muhammed Ashik" <
notifications@github.com>:

**Comment by a5hik** [comment]
Ok, yours is a runtime scenario..how about the dragStart callback?

**Comment by DocX** [comment]
Can be also solution. Get result of dragstart callback. But it would need
change of flow where is the callback called.

What is wrong with attribute value?
Dne 14. 5. 2015 16:16 napsal uživatel "Muhammed Ashik" <
notifications@github.com>:

**Pull request closed without merging**
