### PR TITLE
Add 'grab' and 'grabbing' cursors instead of 'move'

### PR DESCRIPTION
**Pull request by tekdel**
Hi @a5hik,
Could we use new cursors instead of move ?

### CODE REVIEW

**Comment by a5hik** [comment]
@tekdel hope you tested, and thanks for the PR.

**Comment by tekdel** [comment]
@a5hik, many thanks, I've done a build and tests, I will be glad to participate again.

**Comment by tekdel** [comment]
@a5hik, if you are talking about, grab below center of a grabbable block and grabbing it down slow, cursor becomes a default one, so it could be a bug or grabbing behaviour, because It was before my changes.

**Comment by a5hik** [comment]
@tekdel Yeah I see, If there is a problem that exists already..let me merge your changes back.

**Comment by tekdel** [comment]
@a5hik, should I create a pr again?

**Comment by ktracey** [comment]
What if we want the move icons... my product owner wants the move icon but now it is the grabbing icon

**Comment by tekdel** [comment]
I suppose it could be an option, I mean `moveIconClass`: 'grabbing', @a5hik what do you think about it ?

**Comment by a5hik** [comment]
@tekdel I think you should be able to override with ur custom css. the library can have one default option.

**Comment by ktracey** [comment]
The problem with overriding the custom is i can get the move icon during the hover... but then during the drag... it goes to "grabbing" because that is done in the javascript code...

**Pull request merged**
