### PR TITLE
#275 Touch-and-hold for dragging on touch devices

### PR DESCRIPTION
**Pull request by maveric1977**
dragging starts on touch devices first after touch and hold. This way a user can scroll a list by simply dragging and re-order the list by touch-an-hold-dragging.  on iOS devices no oncontextmenu event is fired, implementing a long touch with 500ms

`long-touch` implemented for iOS.
Tested on:

- [x] Android Internet Browser
- [x] Chrome on Android
- [x] Safari on iOS
- [x] Chrome on iOS

### CODE REVIEW

**Comment by a5hik** [comment]
@M4v3R nice PR.. but would be better to control this by providing an 'option'. so that the default behaviour is not affected.

**Comment by maveric1977** [comment]
@a5hik as proposed, there is now a `longTouch` option in the sortable `sortOptions`.

**Comment by a5hik** [comment]
@maveric1977 I merged it!!

and a question, Do we really need the watcher for the option on item handle, It can be at the 'sortable' level and need not be at the 'item' level.

also, did u looked at http://localhost:9009/demo/#/scrollable it has a scrolling container option,. Is this not helpful?

**Comment by maveric1977** [comment]
@a5hik Thanks for the merge.
Since the events are fired by the items, the logic had to be in the item. I also don't like the watcher concept, but putting the option in the item seemed not to make any sense, as we don't want to define a new behaviour for each individual item, but rather a general behaviour for the whole component. 
The watcher was a necessity, as the sortableScope is set after initialization of the items. A better way would be to `$broadcast` an event when the Sortable is ready and listen to it on the items but since this strategy was not used in other components, I did not want to include yet another dependency to the item.

As for the scrollable, I think this functionality does not contradict with the scrollable. In fact a user can mix and match and use both functionalities together now.

**Comment by a5hik** [comment]
@maveric1977 Good. Thanks again for the contribution.

**Comment by a5hik** [comment]
Also I would say this watcher should come in to picture only if the option is set to true. For the default behavior this shouldn't be invoked. I feel the watchers are expensive.

**Pull request merged**
